### ISSUE TITLE
SyntaxError: Unknown token 3:1 in lockfile

### ISSUE THREAD

**Issue by scinos** [atlassian/yarn-dedupe#3]
*Originally reported by* **Anonymous**

----------------------------------------

```
#!javascript

yarn-tools list-duplicates yarn.lock

SyntaxError: Unknown token 3:1 in lockfile
    at Parser.unexpected (C:\Users\predrags\AppData\Local\Yarn\config\global\node_modules\@yarnpkg\lockfile\index.js:4276:11)
    at Parser.parse (C:\Users\predrags\AppData\Local\Yarn\config\global\node_modules\@yarnpkg\lockfile\index.js:4381:14)
    at parse (C:\Users\predrags\AppData\Local\Yarn\config\global\node_modules\@yarnpkg\lockfile\index.js:4450:17)
    at Object.module.exports.exports.default (C:\Users\predrags\AppData\Local\Yarn\config\global\node_modules\@yarnpkg\lockfile\index.js:4062:96)
    at module.exports (C:\Users\predrags\AppData\Local\Yarn\config\global\node_modules\yarn-tools\modules\list-duplicates.js:8:27)
    at Command.commander.command.description.action (C:\Users\predrags\AppData\Local\Yarn\config\global\node_modules\yarn-tools\index.js:17:33)
    at <anonymous>

```

First 30 lines of yarn.lock:

```
#!javascript

# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@mapbox/geojsonhint@2.0.1":
  version "2.0.1"
  resolved "https://registry.yarnpkg.com/@mapbox/geojsonhint/-/geojsonhint-2.0.1.tgz#32dac7300f04b3ebaec74b5ba9853dfb42532354"
  dependencies:
    concat-stream "~1.5.1"
    jsonlint-lines "1.7.1"
    minimist "1.2.0"
    vfile "2.0.0"
    vfile-reporter "3.0.0"

"@sailshq/body-parser@^1.13.3":
  version "1.13.4"
  resolved "https://registry.yarnpkg.com/@sailshq/body-parser/-/body-parser-1.13.4.tgz#313e501619a86273dffd6d1cb916742a5d9e8e1b"
  dependencies:
    "@sailshq/qs" "^4.0.1"
    bytes "2.1.0"
    content-type "~1.0.1"
    debug "~2.2.0"
    depd "~1.0.1"
    http-errors "~1.3.1"
    iconv-lite "0.4.11"
    on-finished "~2.3.0"
    raw-body "~2.1.2"
    type-is "~1.6.6"


```

----------------------------------------
- Bitbucket: https://bitbucket.org/atlassian/yarn-tools/issue/3

**Comment by Bouke** [comment]
I also ran into this. I resolved it by copy and pasting between the resolved file and the actual file. The error was on "line 1, col 0". Maybe there is an a unexpected BOM (utf-8) present?
